cd_timer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('timer/', include('timer.urls')),
    path('admin/', admin.site.urls),
]

timer/urls.py
from django.urls import path
from . import views

app_name = 'timer'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('timers/', views.timers, name='timers'),
    path('timers/new/', views.new_timer, name='new_timer'),
    path('timers/<int:req_pk>/reset/', views.reset_timer, name='reset_timer'),
    path('timers/<int:req_pk>/delete/', views.delete_timer, name='delete_timer'),
]

timer/models.py
from django.db import models

from .consts import *


class User(models.Model):
    username = models.CharField(max_length=USERNAME_LEN_MAX, unique=True)
    password = models.CharField(max_length=PASSWORD_LEN_MAX_REAL)

class Session(models.Model):
    """Browser session ID"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    uuid = models.CharField(max_length=UUID_LEN_MAX)

class Timer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    t_start = models.DateTimeField('When timer was reset')

timer/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.http import HttpResponseNotFound
from django.urls import reverse
from django.utils import timezone

from .models import User, Session, Timer

# App utils
from .utils import *


# Views

######################
# Session management #
######################

def index(request):
    """Manda o cliente para a página de login se a sessão não existir; ou manda ele para a página do usuário (timers)."""
    siface = SessionInterface()
    if siface.get(request) == False:
        return HttpResponseRedirect(reverse('timer:login'))
    else:
        return HttpResponseRedirect(reverse('timer:timers'))


def login(request):
    """Tenta iniciar uma sessão; se o usuário não existir, cria a conta com as credenciais inexistentes e inicia a sessão."""
    tmpl = loader.get_template('timer/login.html')
    if request.method == 'GET':
        return HttpResponse(tmpl.render({ 'error': None }, request))

    else:
        try:
            valid(request.POST['username'], request.POST['password'])
        except (TypeError, ValueError) as error:
            return HttpResponseBadRequest(tmpl.render({ 'error': str(error) }, request))
        
        req_uname = request.POST['username']
        req_hpass = get_password(request)
        siface = SessionInterface()
        
        try:
            u = User.objects.get(username = req_uname)
        except User.DoesNotExist:
            u = User()
            u.username = req_uname
            u.password = req_hpass
            u.save()
            return login(request)
        else:
            if u.password == req_hpass:
                siface.new(u, request)
                return HttpResponseRedirect(reverse('timer:index'))
        return HttpResponseNotFound(tmpl.render({ 'error': '' }, request))


def logout(request):
    """Encerra a sessão e/ou manda para a página de login"""
    siface = SessionInterface()
    if siface.get(request) != False:
        siface.delete(request)

    return HttpResponseRedirect(reverse('timer:login'))


def timers(request):
    """Página do usuário: lista os timers do usuário se este estiver logado"""
    siface = SessionInterface()
    
    if siface.get(request) == False:
        return HttpResponseRedirect(reverse('timer:login'))
    
    user = siface.session.user
    timers = []
    for timer in user.timer_set.all():
        delta = timezone.now() - timer.t_start
        hours = delta.seconds/3600
        mins = (delta.seconds/60)%60
        secs = delta.seconds%60
        # timestr = '%d:%d:%d' % (mins, secs, milis)
        timers.append({
            'pk': timer.pk,
            'days': delta.days,
            'hours': int(hours),
            'mins': int(mins),
            'secs': int(secs)
       })
    
    context = {
        'user': siface.session.user,
        'timers': timers
    }
    return render(request, 'timer/timers.html', context)


#####################
# Timers management #
#####################

def new_timer(request):
    """Cria um timer e atualiza a página do usuário"""
    siface = SessionInterface()
    
    try:
        if siface.get(request) == False:
            raise Session.DoesNotExist
    except Session.DoesNotExist:
        return HttpResponseRedirect(reverse('timer:login'))
    else:
        timer = Timer(user = siface.session.user)
        timer.t_start = timezone.now()
        timer.save()
    return HttpResponseRedirect(reverse('timer:timers'))


def reset_timer(request, req_pk):
    """Reinicia o timer solicitado"""
    siface = SessionInterface()
    
    try:
        if siface.get(request) == False:
            raise Session.DoesNotExist
    except Session.DoesNotExist:
        return HttpResponseRedirect(reverse('timer:login'))
   
    try:
        timer = Timer.objects.get(pk=req_pk)
        if timer.user != siface.session.user:
            raise Timer.DoesNotExist
        
    except Timer.DoesNotExist:
        return HttpResponseNotFound(render_page_error(
            request, 'não encontrado',
            'O timer não foi encontrado ou é de outro proprietário.'))
    else:
        timer.t_start = timezone.now()
        timer.save()
    
    return HttpResponseRedirect(reverse('timer:timers'))


def delete_timer(request, req_pk):
    """Remove o timer solicitado"""
    siface = SessionInterface()
    
    try:
        if siface.get(request) == False:
            raise Session.DoesNotExist
    except Session.DoesNotExist:
        return HttpResponseRedirect(reverse('timer:login'))
    
    try:
        timer = Timer.objects.get(pk=req_pk)
        if timer.user != siface.session.user:
            raise Timer.DoesNotExist
        
    except Timer.DoesNotExist:
        return HttpResponseNotFound(render_page_error(
            request, 'não encontrado',
            'O timer não foi encontrado ou é de outro proprietário.'))
    else:
        timer.delete()
    
    return HttpResponseRedirect(reverse('timer:timers'))

timer/templates/timer/error.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>ERRO: {{ title }}</title>
</head>

<body>
    <div style="text-align: center;">
        <h1 style="color: red;">ERRO</h1>
        <h3>{{ title }}</h3>
        {% if message is not None %}
        <p>{{ message }}</p><br>
        {% endif %}
        <a href="{% url 'timer:index' %}"><button>INÍCIO</button></a>
    </div>
</body>

</html>

timer/templates/timer/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Timer Login</title>
</head>

<body>
    <h1>LOGIN</h1>
    
    {% if error is not None %}
    <h3 style="color: red;">Falha ao acessar!</h3>
        {% if error != '' %}
        <p><strong>ERRO</strong>: {{ error }}</p>
        {% endif %}
    <h5>POSSÍVEIS SOLUÇÕES</p>
    <ol>
        <li>Use um nome de usuário diferente se não possuir uma conta (ver rodapé)</li>
        <li>O nome de usuário deve conter no mínimo 3 caracteres</li>
        <li>A senha deve conter no mínimo 8 caracteres</li>
        <li>Caracteres especiais, com exceção de '_' (sobrelinha) e números, não são permitidos no nome de usuário!</li>
    </ol><br>
    {% endif %}
    
    <h3>Credenciais</h3>
    <form action="{% url 'timer:login' %}" method="POST">
        {% csrf_token %}
        <p>Nome de usuário: <input type="text" name="username" max_length="64"></p>
        <p>Senha: <input type="password" name="password" max_length="128"></p>
        <p>Por favor, salve a sua senha! Não existe recuperação de conta!</p>
        <br>
        <button type="submit">ENTRAR</button>
    </form>

    <br>
    <p>Se você ainda não possui uma conta, tentar entrar com um nome de usuário diferente automaticamente criará uma conta nova.</p>
</body>

</html>

timer/templates/timer/timers.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>@{{ user.username }} timers</title>
</head>
    
<body>
    <h1>@{{ user.username }} timers</h1>
    <a href="{% url 'timer:logout' %}"><button>Troca de usuário (sair)</button></a>
    <a href="{% url 'timer:timers' %}"><button>Sincronizar</button></a>
    <br>
    
    {% for time in timers %}
        <p>{{ forloop.counter }} - <span name="days">{{ time.days }}d - <span name="hours">{{ time.hours }}</span>h<span name="mins">{{ time.mins }}</span>m - <span name="secs">{{ time.secs }}</span>s
        <button onclick="doReset({{ time.pk }});">RESET</button>
        <button onclick="doDelete({{ time.pk }});">DELETE</button></p>
    {% endfor %}
    <br>
    
    <a href="{% url 'timer:new_timer' %}"><button>Adicionar</button></a>
    
    
    <script>
        time_h = document.getElementsByName('hours');
        time_m = document.getElementsByName('mins');
        time_s = document.getElementsByName('secs');
        
        function update() {
            for (var i=0; i < time_h.length; i++) {
                var s = Number(time_s[i].innerHTML);
                var m = Number(time_m[i].innerHTML);
                var h = Number(time_h[i].innerHTML);

                var totalSecs = 1 + s + m*60 + h*3600;

                time_h[i].innerHTML = Math.trunc(totalSecs/3600);
                time_m[i].innerHTML = Math.trunc(totalSecs/60)%60;
                time_s[i].innerHTML = totalSecs%60;
            }
        }
        setInterval(update, 1000);
        
        function doReset(pk) {
            var SIM = confirm("RESETAR TIMER?");
            if (SIM)
                window.location.href = '{% url 'timer:reset_timer' 12345 %}'.replace('12345', pk);
        }
        
        function doDelete(pk) {
            var SIM = confirm("DELETAR TIMER?");
            if (SIM)
                window.location.href = '{% url 'timer:delete_timer' 12345 %}'.replace('12345', pk);
        }
        
    </script>
</body>

</html>